name: Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.html'
      - 'docs/**'
      - 'blog/**'
      - 'static/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  lychee:
    name: Check links with lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: "--verbose --no-progress --exclude-mail"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
